#!/bin/sh
#
# Simple Sider init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:     sider_6379
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Sider data structure server
# Description:          Sider data structure server. See https://sider.io
### END INIT INFO

REDISPORT=6379
EXEC=/usr/local/bin/sider-server
CLIEXEC=/usr/local/bin/sider-cli

PIDFILE=/var/run/sider_${REDISPORT}.pid
CONF="/etc/sider/${REDISPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Sider server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Sider to shutdown ..."
                    sleep 1
                done
                echo "Sider stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
